mybatis:
  config-location: classpath:mybatis/mybatisconfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msc_db?useSSL=false&serverTimezone=UTC&autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date: yyyy-mm-dd
    hiddenmethod:
      filter:
        enabled: true
  mail:
    protocol: smtp #邮件协议
    host: smtp.163.com
    port: 25
    username: fancl0613@163.com
    password: OYZEVHITFQTVXLFZ
    default-encoding: UTF-8
    properties:
      mail:
        debug: true #开启邮件发送过程日志
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 80MB
  thymeleaf:
    encoding: UTF-8
    cache: false
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    com.fcl.fmusic.mapper: DEBUG